name: Compress Images on Push to main branch
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: cleanup auto-compress-images branch
        run: |
          git push -d origin auto-compress-images || echo "no remote branch to cleanup"
          git branch -d auto-compress-images || echo "no local branch to cleanup"
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
          jpegQuality: '100'
          jpegProgressive: true
          pngQuality: '100'
          webpQuality: '100'
      - name: debug
        run: git status && git diff && git branch
      - name: Create New Pull Request If Needed
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v7
        with:
          title: Compressed Images
          branch: auto-compress-images
          branch-suffix: timestamp
          delete-branch: true
          commit-message: Compressed Images
          body: ${{ steps.calibre.outputs.markdown }}